/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/whitebit/protocol/json/instruments_info_ack.hpp"

using namespace roq;
using namespace roq::whitebit;

using namespace std::literals;
using namespace std::chrono_literals;

using value_type = protocol::json::InstrumentsInfoAck;

TEST_CASE("spot", "[json_instruments_info_ack]") {
  auto message = R"({)"
                 R"("retCode":0,)"
                 R"("retMsg":"OK",)"
                 R"("result":{)"
                 R"("category":"spot",)"
                 R"("list":[{)"
                 R"("symbol":"BTCUSDT",)"
                 R"("baseCoin":"BTC",)"
                 R"("quoteCoin":"USDT",)"
                 R"("innovation":"0",)"
                 R"("status":"Trading",)"
                 R"("lotSizeFilter":{)"
                 R"("basePrecision":"0.000001",)"
                 R"("quotePrecision":"0.00000001",)"
                 R"("minOrderQty":"0.00004",)"
                 R"("maxOrderQty":"500",)"
                 R"("minOrderAmt":"1",)"
                 R"("maxOrderAmt":"1200000")"
                 R"(},)"
                 R"("priceFilter":{)"
                 R"("tickSize":"0.01")"
                 R"(})"
                 R"(},{)"
                 R"("symbol":"ETHUSDT",)"
                 R"("baseCoin":"ETH",)"
                 R"("quoteCoin":"USDT",)"
                 R"("innovation":"0",)"
                 R"("status":"Trading",)"
                 R"("lotSizeFilter":{)"
                 R"("basePrecision":"0.00001",)"
                 R"("quotePrecision":"0.0000001",)"
                 R"("minOrderQty":"0.0005",)"
                 R"("maxOrderQty":"100000000",)"
                 R"("minOrderAmt":"1",)"
                 R"("maxOrderAmt":"1200000")"
                 R"(},)"
                 R"("priceFilter":{)"
                 R"("tickSize":"0.01")"
                 R"(})"
                 R"(})"
                 R"(])"
                 R"(},)"
                 R"("retExtInfo":{},)"
                 R"("time":1682255157981)"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.ret_code == 0);
    CHECK(obj.ret_msg == "OK"sv);
  };
  core::json::BufferStack buffers{8192, 1};
  value_type obj{message, buffers};
  helper(obj);
}

TEST_CASE("linear", "[json_instruments_info_ack]") {
  auto message = R"({)"
                 R"("retCode":0,)"
                 R"("retMsg":"OK",)"
                 R"("result":{)"
                 R"("category":"linear",)"
                 R"("list":[{)"
                 R"("symbol":"10000NFTUSDT",)"
                 R"("contractType":"LinearPerpetual",)"
                 R"("status":"Trading",)"
                 R"("baseCoin":"10000NFT",)"
                 R"("quoteCoin":"USDT",)"
                 R"("launchTime":"1643007175000",)"
                 R"("deliveryTime":"0",)"
                 R"("deliveryFeeRate":"",)"
                 R"("priceScale":"6",)"
                 R"("leverageFilter":{)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"12.50",)"
                 R"("leverageStep":"0.01")"
                 R"(},)"
                 R"("priceFilter":{)"
                 R"("minPrice":"0.000005",)"
                 R"("maxPrice":"9.999990",)"
                 R"("tickSize":"0.000005")"
                 R"(},)"
                 R"("lotSizeFilter":{)"
                 R"("maxOrderQty":"445100",)"
                 R"("minOrderQty":"10",)"
                 R"("qtyStep":"10",)"
                 R"("postOnlyMaxOrderQty":"4451000")"
                 R"(},)"
                 R"("unifiedMarginTrade":true,)"
                 R"("fundingInterval":480,)"
                 R"("settleCoin":"USDT")"
                 R"(},{)"
                 R"("symbol":"1000BONKUSDT",)"
                 R"("contractType":"LinearPerpetual",)"
                 R"("status":"Trading",)"
                 R"("baseCoin":"1000BONK",)"
                 R"("quoteCoin":"USDT",)"
                 R"("launchTime":"1672971039000",)"
                 R"("deliveryTime":"0",)"
                 R"("deliveryFeeRate":"",)"
                 R"("priceScale":"6",)"
                 R"("leverageFilter":{)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"25.00",)"
                 R"("leverageStep":"0.01")"
                 R"(},)"
                 R"("priceFilter":{)"
                 R"("minPrice":"0.000001",)"
                 R"("maxPrice":"1.999998",)"
                 R"("tickSize":"0.000001")"
                 R"(},)"
                 R"("lotSizeFilter":{)"
                 R"("maxOrderQty":"8000000",)"
                 R"("minOrderQty":"100",)"
                 R"("qtyStep":"100",)"
                 R"("postOnlyMaxOrderQty":"40000000")"
                 R"(},)"
                 R"("unifiedMarginTrade":true,)"
                 R"("fundingInterval":480,)"
                 R"("settleCoin":"USDT")"
                 R"(})"
                 R"(],)"
                 R"("nextPageCursor":"")"
                 R"(},)"
                 R"("retExtInfo":{},)"
                 R"("time":1682255470701)"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.ret_code == 0);
    CHECK(obj.ret_msg == "OK"sv);
  };
  core::json::BufferStack buffers{8192, 1};
  value_type obj{message, buffers};
  helper(obj);
}

TEST_CASE("inverse", "[json_instruments_info_ack]") {
  auto message = R"({)"
                 R"("retCode":0,)"
                 R"("retMsg":"OK",)"
                 R"("result":{)"
                 R"("category":"inverse",)"
                 R"("list":[{)"
                 R"("symbol":"ADAUSD",)"
                 R"("contractType":"InversePerpetual",)"
                 R"("status":"Trading",)"
                 R"("baseCoin":"ADA",)"
                 R"("quoteCoin":"USD",)"
                 R"("launchTime":"1647302400000",)"
                 R"("deliveryTime":"0",)"
                 R"("deliveryFeeRate":"",)"
                 R"("priceScale":"4",)"
                 R"("leverageFilter":{)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"50.00",)"
                 R"("leverageStep":"0.01")"
                 R"(},)"
                 R"("priceFilter":{)"
                 R"("minPrice":"0.0001",)"
                 R"("maxPrice":"199.9998",)"
                 R"("tickSize":"0.0001")"
                 R"(},)"
                 R"("lotSizeFilter":{)"
                 R"("maxOrderQty":"150000",)"
                 R"("minOrderQty":"1",)"
                 R"("qtyStep":"1",)"
                 R"("postOnlyMaxOrderQty":"750000")"
                 R"(},)"
                 R"("unifiedMarginTrade":false,)"
                 R"("fundingInterval":480,)"
                 R"("settleCoin":"ADA")"
                 R"(},)"
                 R"({)"
                 R"("symbol":"BITUSD",)"
                 R"("contractType":"InversePerpetual",)"
                 R"("status":"Trading",)"
                 R"("baseCoin":"BIT",)"
                 R"("quoteCoin":"USD",)"
                 R"("launchTime":"1636416000000",)"
                 R"("deliveryTime":"0",)"
                 R"("deliveryFeeRate":"",)"
                 R"("priceScale":"4",)"
                 R"("leverageFilter":{)"
                 R"("minLeverage":"1",)"
                 R"("maxLeverage":"50.00",)"
                 R"("leverageStep":"0.01")"
                 R"(},)"
                 R"("priceFilter":{)"
                 R"("minPrice":"0.0001",)"
                 R"("maxPrice":"199.9998",)"
                 R"("tickSize":"0.0001")"
                 R"(},)"
                 R"("lotSizeFilter":{)"
                 R"("maxOrderQty":"100000",)"
                 R"("minOrderQty":"1",)"
                 R"("qtyStep":"1",)"
                 R"("postOnlyMaxOrderQty":"500000")"
                 R"(},)"
                 R"("unifiedMarginTrade":false,)"
                 R"("fundingInterval":480,)"
                 R"("settleCoin":"BIT")"
                 R"(})"
                 R"(],)"
                 R"("nextPageCursor":"")"
                 R"(},)"
                 R"("retExtInfo":{},)"
                 R"("time":1682255697753)"
                 R"(})"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.ret_code == 0);
    CHECK(obj.ret_msg == "OK"sv);
  };
  core::json::BufferStack buffers{8192, 1};
  value_type obj{message, buffers};
  helper(obj);
}

TEST_CASE("option", "[json_instruments_info_ack]") {
  auto message = R"({)"
                 R"("retCode":0,)"
                 R"("retMsg":"success",)"
                 R"("result":{)"
                 R"("category":"option",)"
                 R"("nextPageCursor":"0%2C500",)"
                 R"("list":[{)"
                 R"("symbol":"BTC-29SEP23-80000-C",)"
                 R"("status":"Trading",)"
                 R"("baseCoin":"BTC",)"
                 R"("quoteCoin":"USD",)"
                 R"("settleCoin":"USDC",)"
                 R"("optionsType":"Call",)"
                 R"("launchTime":"1680768000000",)"
                 R"("deliveryTime":"1695974400000",)"
                 R"("deliveryFeeRate":"0.00015",)"
                 R"("priceFilter":{)"
                 R"("minPrice":"5",)"
                 R"("maxPrice":"10000000",)"
                 R"("tickSize":"5")"
                 R"(},)"
                 R"("lotSizeFilter":{)"
                 R"("maxOrderQty":"10000",)"
                 R"("minOrderQty":"0.01",)"
                 R"("qtyStep":"0.01")"
                 R"(})"
                 R"(},)"
                 R"({)"
                 R"("symbol":"BTC-29SEP23-80000-P",)"
                 R"("status":"Trading",)"
                 R"("baseCoin":"BTC",)"
                 R"("quoteCoin":"USD",)"
                 R"("settleCoin":"USDC",)"
                 R"("optionsType":"Put",)"
                 R"("launchTime":"1680768000000",)"
                 R"("deliveryTime":"1695974400000",)"
                 R"("deliveryFeeRate":"0.00015",)"
                 R"("priceFilter":{)"
                 R"("minPrice":"5",)"
                 R"("maxPrice":"10000000",)"
                 R"("tickSize":"5")"
                 R"(},)"
                 R"("lotSizeFilter":{)"
                 R"("maxOrderQty":"10000",)"
                 R"("minOrderQty":"0.01",)"
                 R"("qtyStep":"0.01")"
                 R"(})"
                 R"(})"
                 R"(])"
                 R"(},)"
                 R"("retExtInfo":{},)"
                 R"("time":1682255870318)"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.ret_code == 0);
    CHECK(obj.ret_msg == "success"sv);
  };
  core::json::BufferStack buffers{8192, 1};
  value_type obj{message, buffers};
  helper(obj);
}
