/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/whitebit/protocol/json/wallet_balance_ack.hpp"

using namespace roq;
using namespace roq::whitebit;

using namespace std::literals;

using value_type = protocol::json::WalletBalanceAck;

TEST_CASE("simple", "[json_wallet_balance_ack]") {
  auto message = R"({)"
                 R"("retCode":0,)"
                 R"("retMsg":"OK",)"
                 R"("result":{)"
                 R"("list":[{)"
                 R"("accountIMRate":"0.0001",)"
                 R"("totalMaintenanceMarginByMp":"1.20099314",)"
                 R"("totalInitialMargin":"23.48943389",)"
                 R"("accountType":"UNIFIED",)"
                 R"("accountMMRate":"0",)"
                 R"("accountMMRateByMp":"0",)"
                 R"("accountIMRateByMp":"0.0001",)"
                 R"("totalInitialMarginByMp":"23.48943389",)"
                 R"("totalMaintenanceMargin":"1.20099314",)"
                 R"("totalEquity":"187674.03829067",)"
                 R"("totalMarginBalance":"140743.48632218",)"
                 R"("totalAvailableBalance":"140719.99688829",)"
                 R"("totalPerpUPL":"178.13944266",)"
                 R"("totalWalletBalance":"140564.92491226",)"
                 R"("accountLTV":"0",)"
                 R"("coin":[{)"
                 R"("availableToBorrow":"",)"
                 R"("bonus":"0",)"
                 R"("accruedInterest":"0",)"
                 R"("availableToWithdraw":"",)"
                 R"("totalOrderIM":"0",)"
                 R"("equity":"1.21997126",)"
                 R"("totalPositionMM":"0.00000115",)"
                 R"("usdValue":"136115.2486049",)"
                 R"("unrealisedPnl":"-0.00003782",)"
                 R"("collateralSwitch":true,)"
                 R"("spotHedgingQty":"0",)"
                 R"("borrowAmount":"0.000000000000000000",)"
                 R"("totalPositionIM":"0.00002074",)"
                 R"("walletBalance":"1.22000909",)"
                 R"("cumRealisedPnl":"-0.00015772",)"
                 R"("locked":"0",)"
                 R"("marginCollateral":true,)"
                 R"("coin":"BTC")"
                 R"(},{)"
                 R"("availableToBorrow":"",)"
                 R"("bonus":"0",)"
                 R"("accruedInterest":"0",)"
                 R"("availableToWithdraw":"",)"
                 R"("totalOrderIM":"0",)"
                 R"("equity":"1",)"
                 R"("totalPositionMM":"0",)"
                 R"("usdValue":"4327.631108",)"
                 R"("unrealisedPnl":"0",)"
                 R"("collateralSwitch":false,)"
                 R"("spotHedgingQty":"0",)"
                 R"("borrowAmount":"0.000000000000000000",)"
                 R"("totalPositionIM":"0",)"
                 R"("walletBalance":"1",)"
                 R"("cumRealisedPnl":"0",)"
                 R"("locked":"0",)"
                 R"("marginCollateral":true,)"
                 R"("coin":"ETH")"
                 R"(},{)"
                 R"("availableToBorrow":"",)"
                 R"("bonus":"0",)"
                 R"("accruedInterest":"0",)"
                 R"("availableToWithdraw":"",)"
                 R"("totalOrderIM":"0",)"
                 R"("equity":"2000",)"
                 R"("totalPositionMM":"0",)"
                 R"("usdValue":"923.386",)"
                 R"("unrealisedPnl":"0",)"
                 R"("collateralSwitch":false,)"
                 R"("spotHedgingQty":"0",)"
                 R"("borrowAmount":"0.000000000000000000",)"
                 R"("totalPositionIM":"0",)"
                 R"("walletBalance":"2000",)"
                 R"("cumRealisedPnl":"0",)"
                 R"("locked":"0",)"
                 R"("marginCollateral":true,)"
                 R"("coin":"EOS")"
                 R"(},{)"
                 R"("availableToBorrow":"",)"
                 R"("bonus":"0",)"
                 R"("accruedInterest":"0",)"
                 R"("availableToWithdraw":"",)"
                 R"("totalOrderIM":"0",)"
                 R"("equity":"10000",)"
                 R"("totalPositionMM":"0",)"
                 R"("usdValue":"28068.01",)"
                 R"("unrealisedPnl":"0",)"
                 R"("collateralSwitch":false,)"
                 R"("spotHedgingQty":"0",)"
                 R"("borrowAmount":"0.000000000000000000",)"
                 R"("totalPositionIM":"0",)"
                 R"("walletBalance":"10000",)"
                 R"("cumRealisedPnl":"0",)"
                 R"("locked":"0",)"
                 R"("marginCollateral":true,)"
                 R"("coin":"XRP")"
                 R"(},{)"
                 R"("availableToBorrow":"",)"
                 R"("bonus":"0",)"
                 R"("accruedInterest":"0",)"
                 R"("availableToWithdraw":"",)"
                 R"("totalOrderIM":"0",)"
                 R"("equity":"18237.30054219",)"
                 R"("totalPositionMM":"1.07237652",)"
                 R"("usdValue":"18239.76257777",)"
                 R"("unrealisedPnl":"182.3345",)"
                 R"("collateralSwitch":true,)"
                 R"("spotHedgingQty":"0",)"
                 R"("borrowAmount":"0.000000000000000000",)"
                 R"("totalPositionIM":"21.17247652",)"
                 R"("walletBalance":"18054.96604219",)"
                 R"("cumRealisedPnl":"-46.50745965",)"
                 R"("locked":"0",)"
                 R"("marginCollateral":true,)"
                 R"("coin":"USDT")"
                 R"(})"
                 R"(])"
                 R"(})"
                 R"(])"
                 R"(},)"
                 R"("retExtInfo":{},)"
                 R"("time":1757053660131)"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.ret_code == 0);
    CHECK(obj.ret_msg == "OK"sv);
    REQUIRE(std::size(obj.result.list) == 1);
    REQUIRE(std::size(obj.result.list[0].coin) == 5);
    CHECK(obj.result.list[0].coin[0].coin == "BTC"sv);
    CHECK(obj.result.list[0].coin[4].coin == "USDT"sv);
  };
  core::json::BufferStack buffers{8192, 2};
  value_type obj{message, buffers};
  helper(obj);
}
